* Temas abordados en el transcurso del mes de *octubre*

** Del temario formal

Para desarrollar esta unidad, sugiero que vayamos siguiendo el siguiente
texto que desarrollé hace varios años: [[https://ru.iiec.unam.mx/4047/1/tipos_de_ataque.pdf][Tipos de ataque]]. No está tan
actualizado como quisiera, y tiene varias ligas rotas, pero creo que
podremos utilizarlo para /jugar/ un tanto...

1. =2025.10.02=

   Repasamos las definiciones de /Control de acceso discrecional/ (/DAC/) y
   /Control de acceso mandatorio/ u /obligatorio/ (/MAC/), revisando la
   implementación en Linux con =AppArmor= y =SELinux=.

   Entramos al tema /Tipos de ataque/ abordando el tema /Denegación de
   servicio (DoS)/, cubriendo hasta /amplificación y reflexión/.

2. =2025.10.07=

   Seguimos con los temas faltantes de negación de servicio: Distribuidos
   (/DDoS/), DoS compuestos.

3. =2025.10.09=

   Dado que los alumnos están ya familiarizados con el tema de
   /desbordamiento de buffer/, dimos un paso para profundizar en cómo
   funcionan, y particularmente, en los /desbordamientos de pila/ (/stack
   overflows/): dedicamos la sesión a entender la estructura de los /marcos
   de stack/, el mecanismo empleado para llamar (y salir de) cualquier
   función. Para esto, utilizamos el depurador =gdb=, comparando un par de
   programas ejemplo en C y su compilación a ensamblador, y viendo el
   resultado en ejecución

   Utilizamos el modo TUI de gdb (=gdb --tui=) sobre un par de programas
   compilados con la opción =-g= de =gcc=. Documentación: [[https://www.sourceware.org/gdb/documentation/][GDB: The GNU
   Project Debugger]].

4. =2025.10.14=

   La idea de esta sesión es explorar algunas vulnerabilidades conocidas
   que emplean /distintos tipos/ de desbordamiento. Algunos CVEs para
   /jugar/:

   - CVE-2021-3156 :: Error /off-by-one/ que lleva a un desbordamiento de
     buffer que lleva a una escalación de privilegios a root

   - CVE-2025-3277 :: Desbordamiento de enteros que permite una negación de
     servicio o la ejecución de código arbitrario generando un
     desbordamiento de buffer en /heap/ sobre la función =concat_ws()= de
     SQLite

   - CVE-2025-21333 :: Desbordamiento de enteros que lleva a la elevación
     de privilegios en la integración del núcleo de Hyper-V con el kernel
     de Windows — [[https://whiteknightlabs.com/2025/05/27/understanding-integer-overflow-in-windows-kernel-exploitation/][Explicación y detalles]].

   - CVE-2025-4919 :: Índice fuera de límites mediante una vulnerabilidad
     de confusión de índices en Javascript en Mozilla Firefox y Thunderbird

   - CVE-2025-38204 :: Lectura fuera de índices en la función
     =add_missing_indices()= del subsistema JFS del kernel de Linux

   - Y2K y Y2038 :: Los desbordamientos no únicamente se producen en lo que
     /conocemos como números enteros/...

   *Y para nuestra siguiente clase...* ¡Ahora les toca a ustedes! 😃

   - Busquen alguna vulnerabilidad ≈reciente (<5 años) que lleve a una
     situación de /elevación de privilegios/ utilizando /algún tipo de
     desbordamiento/

   - Descríbanla en un par de párrafos. Describan la naturaleza del
     software vulnerable, y dónde podría estar corriendo que pueda resultar
     /motivo de preocupación/

   - ¿Hay exploits conocidos? Expliquen brevemente cómo funciona el
     exploit. ¿No los hay? expliquen /a grandes rasgos/ qué tipo de datos
     se tendrían que inyectar para /acercarse/ a explotarlo.

   - ¿Hay parches o medidas de mitigación disponibles públicamente?
     Expliquen su funcionamiento.

5. =2025.10.16=

   Como apuntamos, abordamos dos ejemplos de CVE de desbordamiento traídos
   por los alumnos: [[../entregas/02.CVE_escalation/AlfonsoRios/CVE-2024-53141.md][CVE-2024-53141]], sobre el subsistema /netfilter/ del
   núcleo de Linux y [[../entregas/02.CVE_escalation/JRML-EJEMPLO][CVE-2023-4911]] («Looney Tunables»), de la biblioteca de
   C de Linux, /glibc/.

   Comenzamos a hablar de las inyecciones; las inyecciones de SQL son ya
   ampliamente conocidas por el grupo.

6. =2025.10.21= (¿qué fue lo que vimos? ¡Una disculpa! Lo olvidé :-Þ )

7. =2025.10.23= Abordamos el tema de la codificación de texto, siguiendo
   aproximadamente el texto de Joel Spolsky de 2003, [[https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/][The Absolute Minimum
   Every Software Developer Absolutely, Positively Must Know About Unicode
   and Character Sets (No Excuses!)]]

8. =2025.10.28= Continuamos con el tema de codificación de datos, revisando
   la actualización del artículo anterior tras 20 años, [[https://tonsky.me/blog/unicode/][The Absolute
   Minimum Every Software Developer Must Know About Unicode in 2023 (Still
   No Excuses!)]], de Niki Tonsky (2023), y supongo que abordaremos tambien [[https://www.reedbeta.com/blog/programmers-intro-to-unicode/][A
   Programmer’s Introduction to Unicode]], de Nathan Reed (2017).

9. =2025.10.30=

   - Los /modos/ de uso de los algoritmos de cifrado orientados a bloques

   - Fuerza criptográfica comparada de protocolos:
     - [[https://www.keylength.com/][Bluecrypt ⇒ Cryptographic Key Length Recommendation]]
     - [[https://www.enisa.europa.eu/publications/algorithms-key-size-and-parameters-report-2014][Algorithms, key size and parameters report 2014]]

** Temas adicionales abordados

- =2025.10.07=

  Nunca dejan de aparecer pequeños /giros de tuerca/ sobre /agujeros/ ya
  discutidos y analizados. Por ejemplo, el pasado 16 de septiembre, LWN
  presentó el texto [[https://lwn.net/Articles/1038326/][Another npm supply-chain attack]], refiriéndose al
  /ataque de cadena de suministro/ que emplea al paquete de NPM
  /Tinycontrol/, exfiltrando /todo tipo de secretos/. Hay un bonito
  [[https://krebsonsecurity.com/2025/09/self-replicating-worm-hits-180-software-packages/][artículo al respecto en /Krebs on Security/]], y su /modus operandi/
  resuena fuertemente con el [[https://david-gilbertson.medium.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5][artículo de 2018 de David Gilbertson]].

- =2025.10.07=

  Actividad a /intentar/ realizar juntos 😉 /Análisis de tráfico DDoS con
  Wireshark/
  - [[https://www.unb.ca/cic/datasets/ddos-2019.html][CIC-DDoS2019 DDoS evaluation dataset]], del Canadian Institute for
    Cybersecurity
  - [[https://medium.com/@ronak.d.sharma111/analyzing-a-ddos-attack-using-wireshark-8535274cd00e][Analyzing a DDOS Attack Using Wireshark]] (Ronak Sharma, Medium, 2024)
  - [[https://blog.oudel.com/how-to-detect-a-ddos-attack-using-wireshark/][How to Detect a DDoS Attack Using Wireshark?]]
  - Análisis gráfico en línea de interacción en archivos de captura =.pcap=
    → [[https://lab.dynamite.ai][Dynamite Lab]]

