* Temas abordados en el transcurso del mes de *septiembre*

** Del temario «formal»

1. =2025.09.02=
   - (continuando) *Evolución histórica de los retos de seguridad en
     cómputo*
     - 1990s :: Cómputo personal en Internet. Comercialización /
       monetización. Virus/gusanos aprovechando /ingeniería
       social/. Popularización de DoS como ataque. Inyecciones SQL.

       *Ojo* No era tendencia aún (al igual que los primeros virus),
       pero... Primer caso de /ransomware/: /AIDS Trojan/ (1989)
     - 2000s :: Profesionalización y monetización del
       malware. Botnets. Cruce de límites→XSS/CSRF. /OWASP Top 10/
       (2004). /Defensa en profundidad/.
     - Actualidad ::
       Fragmentación del perímetro. Profundización de expresiones de
       /ingeniería social/. Ransomware. Exfiltraciones masivas de datos /en
       la nube/ (→ ¿cuál es tu perímetro?)

2. =2025.09.04= Comenzamos con la unidad 2, /El panorama de la seguridad
   informática hoy/.

   - /Modelos de riesgo/.

     Acercamiento general: Modelos de evaluación de riesgo. [[https://pmstudycircle.com/risk-assessment-models/][Algunos
     apuntadores: 9 Popular Risk Assessment Models in Risk Management]].

     Específico en seguridad informática: [[https://csrc.nist.rip/publications/nistpubs/800-12/800-12-html/chapter7-printable.html][NIST SP 800-12 Cap.7]], [[https://csrc.nist.gov/pubs/sp/800/30/r1/final][NIST SP
     800-30 Rev. 1]]. Los procesos de evaluación y análisis de estos
     documentos de NIST SP 800 son muy completos, pero también demasiado
     “pesados” ⇒ metodología OCTAVE (/Operationally Critical Threat, Asset
     and Vulnerability Evaluation/; Caralli, R. A., Stevens, J. F., Young,
     L. R., & Wilson, W. R. (2007). Introducing OCTAVE Allegro: Improving
     the Information Security Risk Assessment Process. Software
     Engineering Institute, Carnegie Mellon University.), orientada en los
     activos de información y la organización, orientado a que el proceso
     se realice internamente (no con auditor extenro), dando prioridad al
     contexto operativo por sobre la estandarización. [[https://www.sei.cmu.edu/library/introducing-octave-allegro-improving-the-information-security-risk-assessment-process/][Introducing OCTAVE
     Allegro: Improving the Information Security Risk Assessment Process]].

3. =2025.09.09=
   - Presentación de los análisis de riesgo elaborados por los alumnos
   - *Modelos de ataque*

     Catalogan y describen /Tácticas, Técnicas y Procedimientos (TTPs)/ que
     utilizan los adversarios para comprometer sistemas. Los modelos de
     riesgo se centran en /qué queremos y qué requerimos proteger/, nos
     llevan a hacer un análisis del valor de los componentes de nuestra
     información; los modelos de ataque proporcionan /conocimiento
     estructurado/ sobre el comportamiento real desde una perspectiva
     adversarial, pasando de /defensa reactiva/ (corregir vulnerabilidades
     detectadas) a una /defensa proactiva/ (anticipar y detectar campañas de
     ataque).

     - [[https://www.lockheedmartin.com/en-us/capabilities/cyber/cyber-kill-chain.html][Lockheed Martin Cyber Kill Chain]] desarrollado como parte del modelo
       /Intelligence Driven Defense/ para identificar y prevenir actividad
       de intrusiones (2022). Identifica los pasos que un adversario debe
       seguir para montar un reto APT (/Advanced Persistent Threat/), para
       ayudar a romper la cadena. (Ojo: Hay críticas importantes al modelo)

     - [[https://attack.mitre.org/][MITRE ATT&CK]] (2013–, actualización bianual) detalla técnicas para
       distintos entornos, describiendo el /cómo/ y /por qué/ de /cada
       paso/ en el ciclo de vida de un ataque.

     - [[https://d3fend.mitre.org/][MITRE D3FEND]] siguiente paso natural de ATT&CK: «gráfica de
       conocimiento de contramedidas de ciberseguridad»

     - [[https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats#stride][Microsoft STRIDE]] ayuda a modelar y clasificar amenazas y ataques
       para tenerlos presentes de forma preventiva, conforme se desarrolla
       un sistema (y no cuando éste ya está desplegado).

4. =2025.09.23=
   - Concepto y utilidad para rastreo del estado de amenazas de la BD de la
     /[[https://cve.mitre.org][Common Vulnerabilities and Exposures]]/ de MITRE
     - Seguimiento de registros CVE en distribuciones de sistemas
       operativos, por parte de equipos CERT

5. =2025.09.25=
   - Presentación rápida de /[[https://cwe.mitre.org/][Common Weakness Enumeration]]/ CWE de MITRE
     - [[https://cwe.mitre.org/top25/archive/2024/2024_cwe_top25.html][Top 25]]

6. =2025.09.30=
   - Gestión de permisos y privilegios
     - Modelos fundamentales de control de acceso
       - DAC (Discretionary Access Control)
       - MAC (Mandatory Access Control)
       - RBAC (Role-Based Access Control)
       - ABAC (Attribute-Based Access Control)
     - Conceptos relacionados
       - Principio de mínimo privilegio (PoLP)
       - Escalación de privilegios (vertical, horizontal)
       - Acumulación de privilegios (/privilege creep/)
       - Elevación de privilegios /JIT/
       - Separación de responsabilidades (/Separation of Duties/, SoD)

** Temas adicionales abordados
- =2025.09.09= Ataque a cadenas de suministro: [[https://jdstaerk.substack.com/p/we-just-found-malicious-code-in-the][Anatomy of a
  Billion-Download NPM Supply-Chain Attack]]
- =2025.09.23= Revisión rápida y discusión de dos artículos de
  /Communications of the ACM/ de agosto 2025:
  - [[https://cacm.acm.org/opinion/two-types-of-data-privacy-controls/][Two Types of Data Privacy Controls]], Eman Alashwali
  - [[https://cacm.acm.org/research/to-post-or-not-to-post-ai-ethics-in-the-age-of-big-tech/][To Post or Not to Post: AI Ethics in the Age of Big Tech]], Henrik Skaug
    Sætra
- =2025.09.25=
  - Conceptos /muy/ generales de algoritmos de cifrado:
    - RSA
    - Curva elíptica
    - Post-cuántico
